### ISSUE TITLE
Can't access Pkg3 REPL mode

### ISSUE THREAD

**Issue by joshualeond** [KristofferC/OhMyREPL.jl#114] opened 2018-03-19 20:50 UTC
My setup:
On Julia `v"0.7.0-DEV.4631"` for Windows I'm using the `kc/07` branch of OhMyREPL. 

The issue:
It appears that OhMyREPL is blocking the `]` command for REPL mode in Pkg3.

I know there are a lot of moving parts here and that OhMyREPL isn't tagged for `0.7` yet but I thought you may want the feedback.

Thanks for your great work!

**Comment by KristofferC** [comment] 2018-03-19 21:19
Ah, that's interesting. Appreciate the feedback! I think the problem is that I am overwriting the `]` keybinding here: https://github.com/KristofferC/OhMyREPL.jl/blob/aa64547f672e4ceb3c768e30b3b282859f1412f9/src/BracketInserter.jl#L39

I'll have to figure out how to do this so that it doesn't override the Pkg3 keybinding.

**Comment by KristofferC** [comment] 2018-06-27 13:41
Fixed in #112

**Closed by KristofferC** 2018-06-27 13:41 UTC
